### ISSUE TITLE
Upload fails with stamp error

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#462] opened 2022-07-01 15:10 UTC
@michelleplur reported on discord that upload fails with the same error message all the time:

![postage-stamp-screenshot](https://user-images.githubusercontent.com/230163/176921347-f4ace978-524d-458e-9c92-cce3ff29b881.png)

**Comment by Cafe137** [comment] 2022-07-04 11:22
May be caused by https://github.com/ethersphere/bee-dashboard/issues/406

**Comment by Cafe137** [comment] 2022-07-04 11:22
Some occurrences may be fixed by https://github.com/ethersphere/bee-dashboard/pull/463

**Comment by Cafe137** [comment] 2022-07-26 07:02
Should be OK - expired stamps are no longer selectable

**Closed by Cafe137** 2022-07-26 07:02 UTC
Labels: kind:bug, type:issue
