### ISSUE TITLE
Can it support managing multiple bee nodes at the same time?

### ISSUE THREAD

**Issue by pyoy** [ethersphere/bee-dashboard#154] opened 2021-07-03 06:51 UTC
It is found that bee-dashboard can only manage one bee node at the same time, but if multiple bee servers distributed in multiple regions are running, bee-dashboard management is inconvenient

目前发现bee-dashboard在同一时间只能管理一个bee节点，但如果运行了分布在多个地区的多台bee服务器，bee-dashboard管理不方便了

**Comment by pyoy** [comment] 2021-07-03 13:54
Here is a very simple shell to monitor multiple bee nodes, at least the beginning

https://github.com/pyoy/mon_multi_bees/blob/main/mon_multi_bees.sh

**Comment by vojtechsimetka** [comment] 2022-05-02 07:49
Duplicate of #135, closing

**Closed by vojtechsimetka** 2022-05-02 07:49 UTC
Labels: type:issue
