### ISSUE TITLE
Can't connect to the debug api

### ISSUE THREAD

**Issue by bvcofficial** [ethersphere/bee-dashboard#145] opened 2021-06-10 17:21 UTC
## The front-end page connects to the Debug API and reports an error
![1.PNG](https://i.loli.net/2021/06/11/sGgvSPHE89LdwMx.png)
## Here's my bee.yaml file
![2.PNG](https://i.loli.net/2021/06/11/M7oBkSAHymLxcqE.png)

**Comment by vojtechsimetka** [comment] 2021-06-11 17:10
Hi @bvcofficial , thanks for the report. This is very strange indeed, what do you get when you access [`http://localhost:1635/health`](http://localhost:1635/health) in your browser directly? You should see something like:
```json
{
  "status": "ok",
  "version": "0.6.2-984dca0a"
}
```

**Comment by Anthemty** [comment] 2021-06-12 08:14
I have same problem like this. Can't connect to the debug api.

curl http://localhost:1635/health
{"status":"ok","version":"0.6.2-984dca0a"}
@bvcofficial

**Comment by vojtechsimetka** [comment] 2021-06-14 12:24
@Anthemty and do you also have the correct CORS settings and debug port enabled? Can we see that portion of your config file?

**Comment by liuxc0116** [comment] 2021-06-15 10:24
@vojtechsimetka I have same problem like this. Can't connect to the debug api.
curl http://localhost:1635/health
{"status":"ok","version":"0.6.2-984dca0a"}

bee config:

![image](https://user-images.githubusercontent.com/6480317/122036963-b3681300-ce06-11eb-94ac-5a064a98611a.png)

**Comment by vojtechsimetka** [comment] 2021-06-15 10:27
Thanks, @liuxc0116 . This is strange and no idea how can I replicate this. Is there anything in the browser console?

**Comment by liuxc0116** [comment] 2021-06-15 10:41
> Thanks, @liuxc0116 . This is strange and no idea how can I replicate this. Is there anything in the browser console?
I understand. I used the Internet IP to visit the dashboard.
![image](https://user-images.githubusercontent.com/6480317/122039318-24102f00-ce09-11eb-9006-0be09d00e1ba.png)

**Comment by baseonejj** [comment] 2021-06-17 04:03
I'm also experiencing the same problem, which is caused by cross-domain access and occurs when accessing the remote access bee-dashboard

chrome for mac:

`open -n /Applications/Google\ Chrome.app/ --args --disable-web-security --user-data-dir=/tmp`

**Comment by ray-008** [comment] 2021-06-18 05:06
I use docker to run bee，and the config set  BEE_CORS_ALLOWED_ORIGINS='*'  ，not  BEE_CORS_ALLOWED_ORIGINS=['*']

this works for me.

**Comment by marenshuai** [comment] 2021-06-18 13:25
I had the same problem

**Comment by marenshuai** [comment] 2021-06-18 13:27
![image](https://user-images.githubusercontent.com/48117013/122568053-ef57de00-d07b-11eb-8042-ffe9bac89374.png)

**Comment by marenshuai** [comment] 2021-06-18 13:27
![image](https://user-images.githubusercontent.com/48117013/122568125-04cd0800-d07c-11eb-9942-c5a384d68282.png)

**Comment by marenshuai** [comment] 2021-06-18 13:28
![image](https://user-images.githubusercontent.com/48117013/122568235-21694000-d07c-11eb-87c3-790f929f1a7d.png)

**Comment by marenshuai** [comment] 2021-06-18 13:36
Change setting 404

**Comment by marenshuai** [comment] 2021-06-18 13:38
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ray-008** [comment] 2021-06-19 01:26
> has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

set BEE_CORS_ALLOWED_ORIGINS='*'

**Comment by shanelau** [comment] 2021-06-25 01:55
Same issue， set BEE_CORS_ALLOWED_ORIGINS='*'  not working

**Comment by pyoy** [comment] 2021-06-27 14:05
通过浏览器抓包发现，bee-dashboard的客户端（即和bee不在同一台服务器的PC浏览器）在请求1633和1635等端口时，目标地址是localhost，真是愚蠢，难道bee-dashboard只设计在本地运行吗？

Through the browser capture, it is found that when the client of bee-dashboard (that is, the PC browser that is not on the same server as bee) requests ports such as 1633 and 1635, the target address is localhost, which is really stupid. Is the bee-dashboard only designed locally? Is it running?

**Comment by r0achnnan9p** [comment] 2021-07-01 13:38
write the local IP address like 192.168.2.11(not localhost) will be able to solve the problem.

**Comment by vojtechsimetka** [comment] 2022-05-02 07:59
Closing as there are no recent reports.

**Closed by vojtechsimetka** 2022-05-02 07:59 UTC
Labels: type:issue, need:author-input
